export enum TableNames {
    Users = 'users',
    Addresses = 'addresses',
    CustomerProfiles = 'customer_profiles',
    Tokens = 'tokens',
    AdminProfiles = 'admin_profiles',
    RestaurantProfiles = 'restaurant_profiles',
    DriverProfiles = 'driver_profiles',
    MenuCategories = 'menu_categories',
    MenuItems = 'menu_items',
    DriverLocations = 'driver_locations',
    Orders = 'orders',
    OrderItems = 'order_items',
    DeliveryTracking = 'delivery_tracking',
    Payments = 'payments',
    DriverTransactions = 'driver_transactions',
    Reviews = 'reviews',
    Inventories = 'inventories',
    Notifications = 'notifications',
    InventoryTransactions = 'inventory_transaction'
}